# Generated by Django 4.2.5 on 2023-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
