# Generated by Django 4.2.5 on 2023-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_subscriptionupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionupdate',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активно'),
        ),
    ]
