# Generated by Django 4.2.5 on 2023-10-14 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0007_subscriptionupdate_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionUpdate',
            new_name='Subscription',
        ),
    ]
