# Generated by Django 4.2.5 on 2023-10-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата платежа'),
        ),
    ]
