# Generated by Django 4.2.5 on 2023-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='стоимость'),
        ),
    ]
