# Generated by Django 4.2.5 on 2023-10-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_course_amount_remove_lesson_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='стоимость'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='стоимость'),
        ),
    ]
