# Generated by Django 4.2.5 on 2023-10-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
    ]
